config/routes.rb
# frozen_string_literal: true

RailsExecution::Engine.routes.draw do
  root to: 'dashboards#home'

  resource :dashboards, only: [] do
    get :insights
  end

  resources :tasks do
    member do
      get :fork
      patch :reopen
      patch :reject
      patch :approve
      patch :execute
      patch :execute_in_background
    end

    collection do
      get :completed
      get :closed
      get :auto_suggestions
    end

    resources :comments, only: [:create, :update, :destroy]
  end
  resources :labels, only: [:create]
end

app/models/rails_execution/activity.rb
class RailsExecution::Activity < RailsExecution::AppModel

  belongs_to :task

  validates :task, presence: true
  validates :message, presence: true

end

app/models/rails_execution/comment.rb
class RailsExecution::Comment < RailsExecution::AppModel

  belongs_to :task

  validates :task, presence: true
  validates :content, presence: true

end

app/models/rails_execution/label.rb
class RailsExecution::Label < RailsExecution::AppModel
  SPECIAL_LABLES = ['scheduled', 'repeat']
  COLORS = 'red pink purple deep-purple indigo blue light-blue cyan teal green orange deep-orange brown grey blue-grey'.split

  has_many :task_labels, class_name: 'RailsExecution::TaskLabel'
  has_many :tasks, through: :task_labels

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  scope :normal, -> { where.not(name: SPECIAL_LABLES) }

  def color
    color_index = self.name.to_s.chars.sum(&:ord) % COLORS.size
    COLORS[color_index]
  end
end

app/models/rails_execution/task.rb
class RailsExecution::Task < RailsExecution::AppModel

  PROCESSING_STATUSES = %w(created reviewing approved processing rejected)
  ACTIVE_REPEAT_MODE = %w(hourly daily weekly monthly annually weekdays)

  has_many :activities, class_name: 'RailsExecution::Activity'
  has_many :comments, class_name: 'RailsExecution::Comment'
  has_many :task_reviews, class_name: 'RailsExecution::TaskReview'
  has_many :task_labels, class_name: 'RailsExecution::TaskLabel'
  has_many :labels, through: :task_labels
  attr_accessor :reviewer_ids

  validates :title, presence: true
  validates :status, presence: true
  validate :validate_scheduled_at, if: :scheduled_at_changed?

  before_validation :auto_assign_labels

  enum status: {
    created: 'created',
    reviewing: 'reviewing',
    approved: 'approved',
    processing: 'processing', # Processing by background job
    completed: 'completed',
    failed: 'failed',
    rejected: 'rejected',
    closed: 'closed',
  }, _prefix: :is

  enum syntax_status: {
    bad: 'bad',
    good: 'good',
  }, _prefix: true

  enum repeat_mode: {
    none: 'Does not repeat',
    hourly: 'Hourly',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    annually: 'Anually',
    weekdays: 'Every weekday (Monday to Friday)',
  }, _prefix: :repeat

  scope :processing, -> { where(status: PROCESSING_STATUSES) }

  before_update :re_assign_status
  after_commit :create_activity, on: :create, if: :owner

  def in_processing?
    PROCESSING_STATUSES.include?(self.status)
  end

  def scheduled?
    self.scheduled_at? && self.repeat_none?
  end

  def repeatable?
    ACTIVE_REPEAT_MODE.include?(self.repeat_mode)
  end

  def assign_reviewers(ids)
    ids.each do |id|
      next if id.blank?

      task_review = self.task_reviews.find_or_initialize_by({
        owner_id: id,
        owner_type: ::RailsExecution.configuration.owner_model.to_s,
      })
      task_review.status ||= :reviewing
    end
  end

  def assign_labels(ids)
    self.labels = RailsExecution::Label.where(id: ids.uniq)
  end

  def reviewer_ids
    self.task_reviews.pluck(:owner_id)
  end

  def add_files(attachments, current_owner)
    ::RailsExecution.configuration.file_uploader.new(self, attachments, owner: current_owner).call
  end

  def repeat_mode_select_options
    return RailsExecution::Task.repeat_modes if scheduled_at.nil?

    options = RailsExecution::Task.repeat_modes.dup
    options['hourly'] = self.scheduled_at.strftime('Hourly at minute %-M')
    options['daily'] = self.scheduled_at.strftime('Daily at %H:%M')
    options['weekly'] = self.scheduled_at.strftime('Weekly on %A at %H:%M')
    options['monthly'] = self.scheduled_at.strftime('Monthly on %-d at %H:%M')
    options['annually'] = self.scheduled_at.strftime('Annually on %B %-d at %H:%M')
    options['weekdays'] = self.scheduled_at.strftime('Every weekday (Monday to Friday) at %H:%M')
    return options
  end

  def next_time_at
    ::RailsExecution::Services::CreateScheduledJob.new(self).calculate_next_time_at.strftime("%Y-%m-%d %H:%M")
  end

  private

  def create_activity
    self.activities.create(owner: self.owner, message: 'Created the task')
  end

  def re_assign_status
    return if self.is_completed? || self.is_closed?

    if self.is_approved? && (self.script_changed? || self.scheduled_at_changed?)
      self.status = :reviewing
      self.task_reviews.update_all(status: :reviewing)
    end
  end

  def validate_scheduled_at
    return if self.scheduled_at.blank?

    errors.add(:scheduled_at, "Input schedule time #{scheduled_at} is in the past for non-repeat mode") if scheduled_at.past? && repeat_none?
  end

  def auto_assign_labels
    scheduled_label = RailsExecution::Label.find_or_create_by(name: :scheduled)
    repeat_label = RailsExecution::Label.find_or_create_by(name: :repeat)

    final_label_ids = self.label_ids - [scheduled_label.id, repeat_label.id]

    if self.scheduled?
      final_label_ids << scheduled_label.id
    elsif self.repeatable?
      final_label_ids << repeat_label.id
    end

    self.label_ids = final_label_ids
  end

end

app/models/rails_execution/task_label.rb
class RailsExecution::TaskLabel < RailsExecution::AppModel
  belongs_to :task, class_name: 'RailsExecution::Task'
  belongs_to :label, class_name: 'RailsExecution::Label'

  validates :task, uniqueness: { scope: :label }
end

app/models/rails_execution/task_review.rb
class RailsExecution::TaskReview < RailsExecution::AppModel

  belongs_to :task

  validates :task, presence: true
  validates :status, presence: true

  enum status: {
    reviewing: 'reviewing',
    approved: 'approved',
    rejected: 'rejected',
  }, _prefix: :is

  scope :checked, -> { where(status: [:approved, :rejected]) }

end

app/controllers/rails_execution/base_controller.rb
# frozen_string_literal: true

module RailsExecution
  class BaseController < ::ApplicationController

    clear_helpers

    include RailsExecution::BaseHelper
    include RailsExecution::PolicyHelper
    helper RailsExecution::RenderingHelper
    helper RailsExecution::PolicyHelper

    layout 'execution'

  end
end

app/controllers/rails_execution/comments_controller.rb
# frozen_string_literal: true

module RailsExecution
  class CommentsController < ::RailsExecution::BaseController

    def create
      @new_comment = current_task.comments.new(owner: current_owner, content: params.dig(:comment, :content))
      if @new_comment.save
        ::RailsExecution.configuration.notifier.new(current_task).add_comment(current_owner, @new_comment.content)
        current_task.activities.create(owner: current_owner, message: "Added a comment: #{@new_comment.content.truncate(30)}")
      else
        @alert = "Your comment can't adding!"
      end
    end

    def update
      @comment = current_comment
      @comment.update(content: params.dig(:comment, :content))
      respond_to(&:js)
    end

    private

    def current_task
      @current_task ||= RailsExecution::Task.find(params[:task_id])
    end
    helper_method :current_task

    def current_comment
      @comment ||= current_task.comments.find(params[:id])
    end
    helper_method :current_comment

  end
end

app/controllers/rails_execution/dashboards_controller.rb
# frozen_string_literal: true

module RailsExecution
  class DashboardsController < ::RailsExecution::BaseController

    def home
      @in_processing_count = ::RailsExecution::Task.processing.count
      @tasks_count = ::RailsExecution::Task.group(:status).count
    end

    def insights
      @tasks_by_week = ::RailsExecution::Task
        .where(created_at: 10.weeks.ago.beginning_of_day..Time.current)
        .group('YEAR(created_at)', 'WEEK(created_at)')
        .count
      respond_to(&:json)
    end

    private

    def show_insights_chart?
      ::RailsExecution::Task.exists?(created_at: 100.year.ago..1.weeks.ago)
    end
    helper_method :show_insights_chart?

  end
end

app/controllers/rails_execution/labels_controller.rb
# frozen_string_literal: true

module RailsExecution
  class LabelsController < ::RailsExecution::BaseController

    def create
      raise(::RailsExecution::AccessDeniedError, 'Create label') unless can_create_task?

      @label = RailsExecution::Label.new(name: label_name)
      if @label.save
        updated_html = render_to_string(partial: 'rails_execution/tasks/label_collection_select', locals: { selected_label_ids: selected_label_ids })
        render json: { updated_html: updated_html }, status: 200
      else
        render json: @label.errors.full_messages.join(', '), status: 422
      end
    end

    private

    def label_name
      params[:label_name].downcase
    end

    def selected_label_ids
      params[:task_label_ids].to_a.append(@label.id)
    end

  end
end

app/helpers/rails_execution/base_helper.rb
module RailsExecution
  module BaseHelper
    include ActionView::Helpers::AssetUrlHelper

    def current_owner
      return @current_owner if defined?(@current_owner)
      return nil if ::RailsExecution.configuration.owner_method.blank?
      @current_owner = self.send(::RailsExecution.configuration.owner_method)
    end

    def normal_labels
      @normal_labels ||= RailsExecution::Label.normal
    end

  end
end

app/helpers/rails_execution/policy_helper.rb
module RailsExecution
  module PolicyHelper

    def display_owner?(owner)
      owner.present?
    end

    def display_decide?(task)
      task &&
        current_owner &&
        task.owner &&
        current_owner != task.owner &&
        task.syntax_status_good? &&
        !task.is_completed?
    end

    def display_reviewers?(task)
      task.task_reviews.exists?
    end

    def show_form_sidebar?(task)
      return false unless (task.new_record? || task.in_processing?)

      [
        ::RailsExecution.configuration.file_upload,
        !in_solo_mode? && ::RailsExecution.configuration.reviewers.present?,
      ].any?
    end

    def in_solo_mode?
      ::RailsExecution.configuration.solo_mode
    end

    def can_create_task?
      ::RailsExecution.configuration.task_creatable.call(current_owner)
    end

    def can_edit_task?(task)
      ::RailsExecution.configuration.task_editable.call(current_owner, task)
    end

    def can_close_task?(task)
      task.in_processing? && ::RailsExecution.configuration.task_closable.call(current_owner, task)
    end

    def can_execute_task?(task)
      how_to_executable(task).blank?
    end

    def how_to_executable(task)
      return 'Script is empty' if task.script.blank?
      return "Task is closed" if task.is_closed?
      return "It's bad Syntax" if task.syntax_status_bad?
      return "This task is being processed" if task.is_processing?

      unless in_solo_mode?
        return 'This task is not approved' unless task.is_approved?
        return 'No approval from any reviewer' if task.task_reviews.is_approved.empty?
      end

      return "Can't executable by app policy" unless ::RailsExecution.configuration.task_executable.call(current_owner, task)
    end

    def can_schedule_task?(task)
      how_to_schedulable(task).blank?
    end

    def how_to_schedulable(task)
      execute_message = how_to_executable(task)
      return execute_message if execute_message
      return "Time is not set for schedule" if task.scheduled_at.nil?
      return "Scheduled at time in the past" if task.scheduled_at.past?
    end

    def can_remove_scheduled_job?(task)
      task.jid.present?
    end

  end
end

app/helpers/rails_execution/rendering_helper.rb
module RailsExecution
  module RenderingHelper
    AVATAR_CLASS = 'bd-placeholder-img flex-shrink-0 me-2 rounded'
    TRUNCATE_FILE_NAME_LENGTH = 20

    def render_user_info(user, avatar_size: '40x40')
      content_tag :div, class: 'user-info' do
        concat render_owner_avatar(user, size: avatar_size)
        concat render_owner_name(user)
      end
    end

    def render_owner_avatar(owner, size: '32x32')
      return image_tag(asset_path('executions/robot.png'), size: size, class: AVATAR_CLASS) if owner.blank?

      avatar_url = RailsExecution.configuration.owner_avatar.call(owner)
      return nil if avatar_url.blank?

      image_tag avatar_url, size: size, class: AVATAR_CLASS
    end

    def render_owner_name(owner)
      return 'System' if owner.blank?
      return nil if RailsExecution.configuration.owner_name_method.blank?

      content_tag :span, owner.public_send(RailsExecution.configuration.owner_name_method)
    end

    def render_notification_message(mode, message)
      case mode
      when 'alert'
        content_tag :div, class: 'alert alert-warning align-items-center' do
          concat content_tag(:i, nil, class: 'bi bi-x-octagon mr-2')
          concat content_tag(:span, message, class: 'ms-2')
        end
      when 'notice'
        content_tag :div, class: 'alert alert-success align-items-center' do
          concat content_tag(:i, nil, class: 'bi bi-check-circle mr-2')
          concat content_tag(:span, message, class: 'ms-2')
        end
      end
    end

    def render_label(task_label)
      content_tag :div do
        concat content_tag :i, '', class: "bi bi-tag label-colors lc-#{task_label.color} bg-none"
        concat content_tag :span, task_label.name, class: "badge rounded-pill mx-1 label-colors lc-#{task_label.color}"
      end
    end

    def render_task_labels(task)
      # to_a and sort_by instead of .order for avoid N+1 query to sort task labels for each task
      task.labels.to_a.sort_by(&:name).reduce(''.html_safe) do |result, label|
        case label.name
        when 'repeat'
          result + content_tag(:span, "repeat: #{task.repeat_mode}", class: "badge rounded-pill mx-1 label-tag label-colors lc-#{label.color}", data: { id: label.id })
        when 'scheduled'
          result + content_tag(:span, 'scheduled', class: "badge rounded-pill mx-1 label-tag label-colors lc-#{label.color}", data: { id: label.id })
        else
          result + content_tag(:span, label.name, class: "badge rounded-pill mx-1 label-tag label-colors lc-#{label.color}", data: { id: label.id })
        end
      end
    end

    def task_reviewed_status(task)
      @task_reviewed_status ||= {}
      @task_reviewed_status[task] ||= task.task_reviews.find_by(owner_id: current_owner&.id)&.status&.inquiry
    end

    def re_page_actions(&block)
      content_for :page_actions do
        content_tag :span, class: 'ms-2' do
          capture(&block)
        end
      end
    end

    def re_card_content(id: nil, &block)
      content_tag :div, id: id, class: 'my-3 p-3 bg-body rounded shadow-sm' do
        capture(&block)
      end
    end

    def re_render_paging(relation)
      render partial: 'rails_execution/shared/paging', locals: { page: relation.re_current_page, total_pages: relation.re_total_pages }
    end

    def re_attachment_file_acceptable_types
      ::RailsExecution.configuration.acceptable_file_types.keys.join(',')
    end

    def re_get_file_name(url)
      URI(url).path.split('/').last&.truncate(TRUNCATE_FILE_NAME_LENGTH)
    end

    def re_badge_color(status)
      color = status_to_color(status.to_s.downcase.to_sym)
      content_tag :small, status.to_s.titleize, class: "fw-light badge rounded-pill text-bg-#{color}"
    end

    private

    def status_to_color(text)
      {
        bad: 'danger',
        good: 'success',
        closed: 'danger',
        created: 'primary',
        rejected: 'danger',
        approved: 'success',
        reviewing: 'secondary',
        processing: 'warning',
        completed: 'success',
      }[text] || 'secondary'
    end

  end
end

app/views/rails_execution/tasks/_actions.html.haml
- unless current_task.is_completed?
  = re_card_content do
    .text-center
      - if can_execute_task?(current_task)
        = link_to 'Execute NOW!!!', execute_task_path(current_task), class: 'btn btn-block btn-primary', method: :patch, data: { confirm: 'Are you sure?' }
        - if RailsExecution.configuration.task_background
          = link_to 'Execute in background!', execute_in_background_task_path(current_task), class: 'btn btn-block btn-secondary', method: :patch, data: { confirm: 'Are you sure?' }
      - else
        %p.text-danger.mb-0.fw-bold
          %i.bi.bi-x-octagon.me-1
          Not ready to Execute!
        %span.fs-13.text-muted.fw-lighter.mb-0
          %i.bi.bi-megaphone
          = how_to_executable(current_task)

app/views/rails_execution/tasks/_activities.html.haml
- if task_logs.any?
  = re_card_content do
    %h5.section-title Logs
    %ul.list-unstyled#task-logs
      - task_logs.each do |task_log, created_at|
        %li.row.g-0.vetical-align-middle
          .col.d-flex.align-items-center= re_get_file_name(task_log)
          - if created_at
            .col-auto.pe-3
              .activitiy-time.text-muted.text-end
                %span.fs13px= created_at.strftime('%Y/%m/%d')
                %p.mb-0= created_at.strftime('%H:%M')
          .col-auto.text-center
            = link_to task_log, target: :_blank, class: 'text-muted click2download' do
              %i.bi.bi-download.fs-5
              %p.small.mb-0 Download

= re_card_content id: 'activities-section' do
  %h5.section-title Activities
  %ul.list-unstyled
    - current_task.activities.descending.preload(:owner).each do |activitiy|
      %li.row.g-0.vetical-align-middle.mb-3
        .col
          = render_user_info(activitiy.owner, avatar_size: '20x20')
          %p.mb-0.normal-text.mt-1= activitiy.message
        .col-auto.text-end.activitiy-time
          %span.fs13px.text-muted= activitiy.created_at.strftime('%Y/%m/%d')
          %p.mb-0.text-muted= activitiy.created_at.strftime('%H:%M')

app/views/rails_execution/tasks/_attachments.html.haml
%h5.section-title.mb-3 Attachment files
%ul.list-unstyled.mt-3
  - task_attachment_files.each do |name, url|
    %li.normal-text.row.g-0.align-items-center.py-1
      .col-auto
        %i.bi.fs-3.text-muted{ class: "bi-file-text bi-filetype-#{url.split('.').last}" }
      .col.ps-2
        %p.mb-0= name
        %small.text-muted Filename: #{re_get_file_name(url)}
      .col-auto.text-center
        = link_to url, class: 'text-muted' do
          %i.bi.bi-download.fs-5
          %p.small.mb-0 Download

app/views/rails_execution/tasks/_comments.html.haml
= render partial: 'new_comment', locals: { comment: (new_comment || current_task.comments.new) }
= render current_task.comments.ascending.preload(:owner)

:javascript
  hljs.highlightAll();
  window.comments.initAddNewComment('comment_content');

  $(document).on('click', '.media-comment a.edit-comment', function() {
    window.comments.clickEditComment(this);
    return false;
  });
  $(document).on('click', '.media-comment a.cancel-edit-mode', function() {
    window.comments.cancelEditMode(this);
    return false;
  });

app/views/rails_execution/tasks/_form.html.haml
= form_for task, method: task.new_record? ? :post : :patch, html: { enctype: 'multipart/form-data' } do |f|
  .row
    - if task.errors.any?
      .col-12.text-danger.mt-3= task.errors.full_messages.join("\n")

    .col
      .mb-3.mt-4= f.text_field :title, { class: 'form-control', placeholder: 'Title', required: true }
      .mb-3.mt-4= f.text_area :description, { class: 'form-control', placeholder: 'Description', rows: 10 }
    - if show_form_sidebar?(task)
      .col-4
        - unless in_solo_mode?
          %h5.mb-2.mt-4.section-title Reviewers
          #reviewers.mb-3
            - if reviewers.any?
              = f.collection_select :task_review_ids, reviewers, :id, :name, { selected: task.reviewer_ids }, { multiple: true, class: 'select2 col-12' }
            - else
              %p.small.text-muted Nobody can be added
        %h5.mb-2.mt-4.section-title
          Labels
          .float-end
            = link_to '#', class: 'text-primary', 'data-bs-target': '#newLabelModalForm', 'data-bs-toggle': "modal" do
              %i.bi.bi-plus-circle.me-1
              Add
        #labels.mb-3
          = render partial: 'label_collection_select', locals: { selected_label_ids: task.label_ids }
        - if RailsExecution.configuration.task_schedulable
          %h5.mb-2.mt-4.section-title
            Scheduler
            %i.bi.bi-clock-fill.me-1.pointer-events
            %a{:href => "#", id: "clear-schedule-btn"} clear
          = f.datetime_local_field :scheduled_at, class: "form-control", placeholder: "Select Datetime"
          = f.select :repeat_mode, options_for_select(task.repeat_mode_select_options.invert, f.object.repeat_mode), {}, class: "form-control", disabled: !task.scheduled_at?
        - if RailsExecution.configuration.file_upload
          .mt-4= render partial: 'attachments', locals: { task_attachment_files: task_attachment_files }
          #attachment_files.mb-3
            %ul.list-unstyled= render partial: 'attachment_file_fields'

            .mt-3.text-center
              %hr.smoothly
              = link_to 'More file', '#add-more-file', data: { fields_html: render(partial: 'attachment_file_fields') }, class: 'btn text-primary', id: 'js-add-more-file'

    - if task.new_record? || task.in_processing?
      .col-md-12.mb-3.mt-3
        .row
          .col
            %h5.section-title Script
          .col.text-end= render partial: 'tips'
        = f.text_area :script, { class: 'form-control hidden', rows: 3, id: 'main-script' }
        #script-editor-container
          #script-editor= task.script
          = link_to '#full-screen', class: 'btn', id: 'click2full' do
            %i.bi.bi-arrows-fullscreen
            %i.bi.bi-arrows-angle-contract

  .mb-3.mt-3.text-end
    %hr
    = f.submit (task.new_record? ? 'Create' : 'Update'), class: 'btn btn-success'

= render partial: 'form_scripts', locals: { task: task }
= render partial: 'new_label_modal_form'

:javascript
  $(document).ready(function() {
    $('#task_scheduled_at').change(function() {
      var scheduledAtValue = $(this).val();
      var modeSelect = $('#task_repeat_mode');
      modeSelect.prop('disabled', false);

      var scheduledDate = new Date(scheduledAtValue);
      var currentMinutes = scheduledDate.getMinutes().toString().padStart(2, '0');
      var currentHours = scheduledDate.getHours().toString().padStart(2, '0');
      var currentDayOfWeek = scheduledDate.toLocaleDateString('en-US', { weekday: 'long' });
      var currentDayOfMonth = scheduledDate.getDate();
      var currentMonth = scheduledDate.toLocaleDateString('en-US', { month: 'long' });

      modeSelect.find('option[value="hourly"]').text(`Hourly at minute ${scheduledDate.getMinutes()}`);
      modeSelect.find('option[value="daily"]').text(`Daily at ${currentHours}:${currentMinutes}`);
      modeSelect.find('option[value="weekly"]').text(`Weekly on ${currentDayOfWeek} at ${currentHours}:${currentMinutes}`);
      modeSelect.find('option[value="monthly"]').text(`Monthly on ${currentDayOfMonth} at ${currentHours}:${currentMinutes}`);
      modeSelect.find('option[value="annually"]').text(`Annually on  ${currentMonth} ${currentDayOfMonth} at ${currentHours}:${currentMinutes}`);
      modeSelect.find('option[value="weekdays"]').text(`Every weekday (Monday to Friday) at ${currentHours}:${currentMinutes}`);
    });

    $('#clear-schedule-btn').on('click', function() {
      $('#task_scheduled_at').val('');

      var modeSelect = $('#task_repeat_mode');
      modeSelect.val('none');
      modeSelect.prop('disabled', true);
    });
  });

app/views/rails_execution/tasks/_label_collection_select.html.haml
= select_tag 'task_label_ids', options_for_select(normal_labels.map { |l| [l.name, l.id, { color: l.color }] }, selected_label_ids), { multiple: true, class: 'select2 col-12' }

:javascript
  $('#task_label_ids').select2({
    dropdownCssClass: 'labeling',
    templateSelection: function(data, container) {
      if (data.id == '') {
        return data.text;
      } else {
        return $('<span class="label-colors lc-' + $(data.element).attr('color') + '">' + data.text + '</span>');
      }
    },
    templateResult: function(data, container) {
      if (data.id == '') {
        return data.text;
      } else {
        return $('<span class="badge label-colors lc-' + $(data.element).attr('color') + '">' + data.text + '</span>');
      }
    }
  });

app/views/rails_execution/tasks/_labels.html.haml
- if current_task.labels.any?
  .py-2.text-end= render_task_labels(current_task)

app/views/rails_execution/tasks/_new_comment.html.haml
#new-comment
  = re_card_content do
    = form_for comment || current_task.comments.new, url: task_comments_path(current_task), remote: true do |f|
      = f.text_area :content, { rows: 3 }
      .mt-3
        .text-start.text-danger= alert
        .text-end= f.submit 'Comment', class: 'btn btn-outline-success'

app/views/rails_execution/tasks/_quick_filter.html.haml
.d-flex.mt-2
  %button.btn.quick-filter-btn{ type: 'button', 'data-target': '#my_task' }
    - if params[:my_task] == '1'
      %i.bi.bi-check-square
    - else
      %i.bi.bi-square
    Only my tasks
    = hidden_field_tag :my_task, params[:my_task]
  %button.btn.quick-filter-btn{ type: 'button', 'data-target': '#recently_updated' }
    - if params[:recently_updated] == 'asc'
      %i.bi.bi-sort-numeric-down
    - else
      %i.bi.bi-sort-numeric-down-alt
    Last updated
    = hidden_field_tag :recently_updated, params[:recently_updated]

:javascript
  $(document).ready(function() {
    $('.quick-filter-btn').on('click', function() {
      var isFilterActivatedInput = $($(this).attr('data-target'));
      var isFilterActivated = isFilterActivatedInput.val() == 'asc' ? 'desc' : 'asc';
      isFilterActivatedInput.val(isFilterActivated)
      $('#filter-form').submit();
    })
  })

app/views/rails_execution/tasks/_reviewers.html.haml
- if display_reviewers?(current_task)
  = re_card_content do
    %h5.section-title Reviewers
    %ul.list-unstyled.mt-3
      - if reviewing_accounts.empty?
        %li.mt-2.small.text-muted.text-center Nobody!
      - else
        - reviewing_accounts.each do |task_review|
          %li.mt-2
            .row
              .col= render_user_info(task_review.owner, avatar_size: '20x20')
              .col-3.text-end= re_badge_color(task_review.status)

- if display_decide?(current_task)
  = re_card_content do
    %h5.section-title What is your decision?
    .row.mt-3
      .col= render_user_info(current_owner, avatar_size: '20x20')
      .col-6.text-end
        - unless task_reviewed_status(current_task)&.rejected?
          = link_to 'Reject', reject_task_path(current_task), method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
        - unless task_reviewed_status(current_task)&.approved?
          = link_to 'Approve', approve_task_path(current_task), method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-success'

app/views/rails_execution/tasks/_show_scripts.html.haml
- if current_task.script.present?
  :javascript
    window.editor = ace.edit("script-editor", {
      wrap: true,
      readOnly: true,
      printMarginColumn: false,
    });
    var RubyMode = ace.require("ace/mode/ruby").Mode;
    editor.setTheme("ace/theme/solarized_dark");
    editor.session.setMode(new RubyMode());

    $('#click2detail').click(function() {
      this.remove();
      $('#script-editor').removeClass('collapsed');
      window.editor.resize();
      return false;
    })
    $('#click2full').click(function() {
      $('#task-detail').toggleClass('fullscreen');
      window.editor.resize();
      return false;
    })

- if current_task.description.present?
  :javascript
    $('#description-html').html(marked.parse($('#description-markdown').html()));
    hljs.highlightAll();