config/routes.rb
# frozen_string_literal: true

RailsExecution::Engine.routes.draw do
  root to: 'dashboards#home'

  resource :dashboards, only: [] do
    get :insights
  end

  resources :tasks do
    member do
      get :fork
      patch :reopen
      patch :reject
      patch :approve
      patch :execute
      patch :execute_in_background
    end

    collection do
      get :completed
      get :closed
      get :auto_suggestions
    end

    resources :comments, only: [:create, :update, :destroy]
  end
  resources :labels, only: [:create]
end

app/controllers/rails_execution/dashboards_controller.rb
# frozen_string_literal: true

module RailsExecution
  class DashboardsController < ::RailsExecution::BaseController

    def home
      @in_processing_count = ::RailsExecution::Task.processing.count
      @tasks_count = ::RailsExecution::Task.group(:status).count
    end

    def insights
      @tasks_by_week = ::RailsExecution::Task
        .where(created_at: 10.weeks.ago.beginning_of_day..Time.current)
        .group('YEAR(created_at)', 'WEEK(created_at)')
        .count
      respond_to(&:json)
    end

    private

    def show_insights_chart?
      ::RailsExecution::Task.exists?(created_at: 100.year.ago..1.weeks.ago)
    end
    helper_method :show_insights_chart?

  end
end

app/views/rails_execution/dashboards/charts/_insights.html.haml
= re_card_content do
  %h5.section-title Insights
  %canvas{ id: :insights_chart, height: 300 }

:javascript
  $.get("#{insights_dashboards_path(:json)}", function(data) {
    new Chart(document.getElementById('insights_chart').getContext('2d'), {
      type: 'line',
      data: data,
      options: {
        responsive: true,
        plugins: {
          legend: false,
        },
        layout: {
          padding: 20,
        },
        scales: {
          y: {
            min: 0,
            ticks: { stepSize: 1 },
            grid: { display: false },
          },
        },
      },
    });
  });